version: 2
jobs:
  gcc_5:
    docker:
      - image: gcc:5
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  gcc_7:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  gcc_8:
    docker:
      - image: gcc:8
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_3_3:
    docker:
      - image: teeks99/clang-ubuntu:3.3
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_3_4:
    docker:
      - image: teeks99/clang-ubuntu:3.4
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_3_5:
    docker:
      - image: teeks99/clang-ubuntu:3.5
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_3_6:
    docker:
      - image: teeks99/clang-ubuntu:3.6
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_3_7:
    docker:
      - image: teeks99/clang-ubuntu:3.7
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_3_8:
    docker:
      - image: teeks99/clang-ubuntu:3.8
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_3_9:
    docker:
      - image: teeks99/clang-ubuntu:3.9
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_4:
    docker:
      - image: teeks99/clang-ubuntu:4
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_5:
    docker:
      - image: teeks99/clang-ubuntu:5
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_6:
    docker:
      - image: teeks99/clang-ubuntu:6
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_7:
    docker:
      - image: teeks99/clang-ubuntu:7
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_8:
    docker:
      - image: teeks99/clang-ubuntu:8
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_9:
    docker:
      - image: teeks99/clang-ubuntu:9
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc_5
      - gcc_6
      - gcc_7
      - gcc_8
      - clang_3_3
      - clang_3_4
      - clang_3_5
      - clang_3_6
      - clang_3_7
      - clang_3_8
      - clang_3_9
      - clang_4
      - clang_5
      - clang_6
      - clang_7
      - clang_8
      - clang_9
