version: 2
jobs:
  gcc_4_8:
    docker:
      - image: gcc:4.8
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  gcc_8:
    docker:
      - image: gcc:8
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_3_3:
    docker:
      - image: teeks99/clang-ubuntu:3.3
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_5:
    docker:
      - image: teeks99/clang-ubuntu:5
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_6:
    docker:
      - image: teeks99/clang-ubuntu:6
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check
  clang_9:
    docker:
      - image: teeks99/clang-ubuntu:9
    steps:
      - checkout
      - run:
          name: Run check-syle
          command: make check-style
      - run:
          name: Run make
          command: make
      - run:
          name: Run make check
          command: make check

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc_4_8
      - gcc_8
      - clang_3_3
      - clang_5
      - clang_6
      - clang_9
